packages:
  - 'packages/**/*'
  - 'configs/**/*'

catalog:
  clsx: 2.1.1
  vite: 5.0.12
  vitest: 1.2.2
  "@vitejs/plugin-react": 4.2.1
  jsdom: 24.0.0
  "@testing-library/react": 14.1.2
  react: 18.2.0
  react-dom: 18.2.0
  "@storybook/addon-controls": "8.2.0"
  "@storybook/cli": "8.2.0"
  "@storybook/react": "8.2.0"
  "@storybook/react-vite": "8.2.0"
  tailwindcss: 3.4.10
