packages:
  - 'app'
  - 'storybook'
  - 'packages/**/*'
  - 'configs/**/*'
  - 'features/**/*'
  - 'tests/**/*'
allowBuilds:
  '@firebase/util': true
  esbuild: true
  protobufjs: true
  re2: true

catalog:
  # build:vite

  # dev:tools
  '@dotenvx/dotenvx': 2.1.4
  "@firebase/rules-unit-testing": 5.0.1
  '@hookform/resolvers': 5.4.0

  # test:playwright
  '@playwright/test': 1.61.1
  "@pnpm/find-workspace-dir": 1000.1.5
  "@storybook/addon-controls": 9.0.8
  "@storybook/react": 10.4.6
  "@storybook/react-vite": 10.4.6
  "@testing-library/dom": 10.4.1
  "@testing-library/react": 16.3.2
  "@testing-library/user-event": 14.6.1
  '@types/crypto-js': 4.2.2

  # type:node
  '@types/node': 26.1.0
  "@types/react": 19.2.17
  "@types/react-dom": 19.2.3

  "@types/react-transition-group": 4.4.12
  "@types/sinon": 22.0.0
  # dev:vanilla-extract
  '@vanilla-extract/css': 1.21.1
  '@vanilla-extract/vite-plugin': 5.2.3
  "@vitejs/plugin-react": 6.0.3
  "concurrently": 10.0.3

  # lib:crypto-js
  'crypto-js': 4.2.0

  # dev:eslint and related
  "eslint": 10.6.0
  "eslint-config-prettier": 10.1.8
  "eslint-plugin-react": 7.37.5
  "eslint-plugin-react-hooks": 7.1.1
  "eslint-plugin-unused-imports": 4.4.1
  firebase: 12.15.0

  # lib:firebase
  firebase-tools: 15.22.4

  # lib:immer
  immer: 11.1.11

  # lib:jotai
  "jotai": 2.20.1

  # test:testing-librry
  jsdom: 29.1.1

  # lib:react
  react: 19.2.7
  react-dom: 19.2.7

  # lib:react-hook-form
  react-hook-form: 7.80.0
  # test:sinon
  "sinon": 22.0.0

  # dev:storybook
  storybook: 10.4.6

  # dev:typescript
  typescript: 6.0.3
  "typescript-eslint": 8.62.1

  # lib:uuid
  uuid: 14.0.1
  vite: 8.1.3
  vitest: 4.1.9

  # lib: wouter
  wouter: 3.10.0

  # lib:zod
  zod: 4.4.3
