packages:
  - 'packages/**/*'
  - 'configs/**/*'
  - 'app'
  - 'features/**/*'

catalog:
  clsx: 2.1.1
  vite: 5.0.12
  vitest: 1.2.2
  "@vitejs/plugin-react": 4.2.1
  jsdom: 24.0.0
  "@testing-library/react": 14.1.2
  react: 18.2.0
  react-dom: 18.2.0
  "@storybook/addon-controls": "8.2.0"
  "@storybook/cli": "8.2.0"
  "@storybook/react": "8.2.0"
  "@storybook/react-vite": "8.2.0"
  tailwindcss: 3.4.10
  "eslint": "^9.9.0"
  "eslint-config-prettier": "^9.1.0"
  "eslint-plugin-react": "^7.35.0"
  "eslint-plugin-unused-imports": "^4.1.3"
  "typescript-eslint": "^8.1.0"
  "concurrently": "8.2.2"
  "jotai": "2.9.3"
