/**
 * Icons to be able to use with Icon component
 */
export enum Icons {
  allowBackUp = "arrow-back-up",
  check = "check",
  chevronDown = "chevron-down",
  chevronLeft = "chevron-left",
  chevronRight = "chevron-right",
  circleArrowLeft = "circle-arrow-left",
  clipboardCheck = "clipboard-check",
  clipboard = "clipboard",
  clockHour1 = "clock-hour-1",
  clockHour2 = "clock-hour-2",
  clockHour3 = "clock-hour-3",
  clockHour4 = "clock-hour-4",
  clockHour5 = "clock-hour-5",
  clockHour6 = "clock-hour-6",
  clockHour7 = "clock-hour-7",
  clockHour8 = "clock-hour-8",
  clockHour9 = "clock-hour-9",
  clockHour10 = "clock-hour-10",
  clockHour11 = "clock-hour-11",
  clockHour12 = "clock-hour-12",
  doorExit = "door-exit",
  equal = "equal",
  eye = "eye",
  loader2 = "loader-2",
  main = "mail",
  pencil = "pencil",
  settings = "settings",
  userX = "user-x",
  user = "user",
  users = "users",
  x = "x",
}
