import { GameRepository } from "./domains/game-repository";
import { RoundRepository } from "./domains/round-repository";
import { UserRepository } from "./domains/user-repository";
import { GameObserver, RoundObserver, UserObserver } from "./infrastractures/observer";
import { Query } from "./status/query-models/round-history";
import { Authenticator } from "./status/type";
import { ChangeThemeUseCase } from "./usecases/change-theme";
import { ChangeUserModeUseCase } from "./usecases/change-user-mode";
import { ChangeUserNameUseCase } from "./usecases/change-user-name";
import { CreateGameUseCase } from "./usecases/create-game";
import { EstimatePlayerUseCase } from "./usecases/estimate-player";
import { JoinUserUseCase } from "./usecases/join-user";
import { KickPlayerUseCase } from "./usecases/kick-player";
import { LeaveGameUseCase } from "./usecases/leave-game";
import { NewRoundUseCase } from "./usecases/new-round";
import { ShowDownUseCase } from "./usecases/show-down";
import { DependencyRegistrar } from "./utils/dependency-registrar";

export type Dependencies = {
  userRepository: UserRepository;
  userObserver: UserObserver;
  roundObserver: RoundObserver;
  changeUserNameUseCase: ChangeUserNameUseCase;
  roundHistoryQuery: Query;
  gameRepository: GameRepository;
  roundRepository: RoundRepository;
  createGameUseCase: CreateGameUseCase;
  estimatePlayerUseCase: EstimatePlayerUseCase;
  showDownUseCase: ShowDownUseCase;
  newRoundUseCase: NewRoundUseCase;
  changeUserModeUseCase: ChangeUserModeUseCase;
  joinUserUseCase: JoinUserUseCase;
  leaveGameUseCase: LeaveGameUseCase;
  authenticator: Authenticator;
  gameObserver: GameObserver;
  kickPlayerUseCase: KickPlayerUseCase;
  changeThemeUseCase: ChangeThemeUseCase;
};

export type ApplicationDependencyRegistrar = DependencyRegistrar<Dependencies>;
